import { createFileRoute, Link } from '@tanstack/react-router'
import { api } from '../api/client'
import { Button } from '../components/ui/Button'
import { Card, CardHeader, CardTitle, CardContent } from '../components/ui/Card'
import { Badge } from '../components/ui/Badge'
import { ArrowLeft, Download, Copy, Maximize2 } from 'lucide-react'
import { useState, useEffect } from 'react'

export const Route = createFileRoute('/tasks/$taskId/artifacts/$artifactId')({
    component: ArtifactViewerPage,
    loader: async ({ params }) => {
        return {
            task: await api.getTask(params.taskId),
            artifact: await api.getArtifact(params.taskId, params.artifactId)
        }
    }
})

function ArtifactViewerPage() {
    const { task, artifact } = Route.useLoaderData()
    const [content, setContent] = useState<string>("Loading content...")

    useEffect(() => {
        api.getArtifactContent(task.id, artifact.id)
            .then(setContent)
            .catch(e => setContent(`Error loading content: ${e.message}`))
    }, [task.id, artifact.id])

    return (
        <div className="space-y-6 h-[calc(100vh-140px)] flex flex-col">
            {/* Breadcrumb */}
            <div className="flex items-center gap-2 text-sm text-neutral-500">
                <Link to="/tasks/$taskId" params={{ taskId: task.id }} className="hover:text-neutral-900">{task.id}</Link>
                <span>/</span>
                <span className="font-medium text-neutral-900">{artifact.name}</span>
            </div>

            <Card className="flex-1 flex flex-col overflow-hidden border-neutral-300 shadow-sm">
                <div className="flex justify-between items-center p-4 border-b border-neutral-200 bg-neutral-50">
                    <div className="flex items-center gap-3">
                        <div className="font-mono font-medium text-neutral-900">{artifact.name}</div>
                        <Badge variant="outline" className="bg-white">{artifact.type}</Badge>
                        <span className="text-xs text-neutral-500">{artifact.size_bytes}B</span>
                    </div>
                    <div className="flex gap-2">
                        <Button variant="ghost" size="sm"><Copy className="w-4 h-4 mr-2" /> Copy</Button>
                        <Button variant="ghost" size="sm"><Download className="w-4 h-4 mr-2" /> Download</Button>
                        <Button variant="ghost" size="sm"><Maximize2 className="w-4 h-4" /></Button>
                    </div>
                </div>

                <div className="flex-1 overflow-auto bg-[#1E1E2E] p-6">
                    <pre className="font-mono text-sm text-neutral-300 leading-relaxed whitespace-pre-wrap">
                        <code>{content}</code>
                    </pre>
                </div>

                <div className="p-3 border-t border-neutral-200 bg-neutral-50 text-xs text-neutral-500 flex justify-between">
                    <div>Generated by {task.agent_id || 'System'}</div>
                    <div className="flex gap-4">
                        <span className="flex items-center gap-1 text-emerald-600">Gate 1 ✓</span>
                        <span className="flex items-center gap-1 text-emerald-600">Gate 2 ✓</span>
                    </div>
                </div>
            </Card>
        </div>
    )
}
