
import { ApiClient } from '../../frontend/src/api/client';
import type { Task } from '../../frontend/src/api/types';

const api = new ApiClient('http://localhost:8000');

// Mock crypto for node environment if needed, or assume Node 19+
if (!globalThis.crypto) {
    // @ts-ignore
    globalThis.crypto = require('crypto');
}

async function runE2ETest() {
    console.log("🚀 Starting E2E Pipeline Test...");

    try {
        // 1. Health Check
        console.log("\n1. Checking System Health...");
        const health = await api.getHealth();
        console.log("   Health Status:", health.services);
        if (!health.services.api) throw new Error("API is unhealthy");

        // 2. Submit Task (Sandbox)
        console.log("\n2. Submitting Sandbox Task...");
        const task = await api.createTask({
            description: "E2E Test Task - generated by automated test",
            environment: "SANDBOX",
            priority: "LOW"
        });
        console.log(`   Task Created: ${task.id} [${task.state}]`);
        if (task.state !== 'SUBMITTED' && task.state !== 'PLANNING') {
            console.warn("   Warning: Task did not start in SUBMITTED/PLANNING");
        }

        // 3. Poll for Updates (Simulate Agent work)
        console.log("\n3. Polling for updates...");
        let currentTask = task;
        let attempts = 0;
        while (!['COMPLETED', 'FAILED', 'CANCELLED', 'APPROVAL_PENDING'].includes(currentTask.state) && attempts < 10) {
            await new Promise(r => setTimeout(r, 1000));
            currentTask = await api.getTask(task.id);
            process.stdout.write(`   [${currentTask.state}] `);
            attempts++;
        }
        console.log(`\n   Final Polled State: ${currentTask.state}`);

        // 4. Test Approval Logic (if applicable)
        if (currentTask.state === 'APPROVAL_PENDING') {
            console.log("\n4. Testing Approval Flow...");
            await api.updateTaskState(task.id, 'approve', { comment: "E2E Auto-Approval" });
            console.log("   Approved. Waiting for completion...");

            attempts = 0;
            while (!['COMPLETED', 'FAILED'].includes(currentTask.state) && attempts < 10) {
                await new Promise(r => setTimeout(r, 1000));
                currentTask = await api.getTask(task.id);
                process.stdout.write(`   [${currentTask.state}] `);
                attempts++;
            }
        }

        // 5. Verify Artifacts
        console.log("\n5. Verifying Artifacts...");
        if (currentTask.artifacts && currentTask.artifacts.length > 0) {
            console.log(`   Found ${currentTask.artifacts.length} artifacts.`);
            const content = await api.getArtifactContent(currentTask.id, currentTask.artifacts[0].id);
            console.log(`   Artifact[0] content length: ${content.length}`);
        } else {
            console.log("   No artifacts produced (expected for simple test).");
        }

        console.log("\n✅ E2E Test Passed!");

    } catch (e: any) {
        console.error("\n❌ E2E Test Failed:", e.message);
        // We don't exit(1) here because we might be running against a mock/down server
        // and want to report that state rather than crash the test runner if wrapped.
        if (e.message.includes("fetch failed") || e.message.includes("ECONNREFUSED")) {
            console.warn("   (Backend appears to be down. Use 'mock' mode or start backend.)");
        }
    }
}

runE2ETest();
