/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksNewRouteImport } from './routes/tasks.new'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as DevComponentsRouteImport } from './routes/dev.components'
import { Route as TasksTaskIdIndexRouteImport } from './routes/tasks.$taskId.index'
import { Route as TasksTaskIdReviewRouteImport } from './routes/tasks.$taskId.review'
import { Route as TasksTaskIdArtifactsArtifactIdRouteImport } from './routes/tasks.$taskId.artifacts.$artifactId'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksNewRoute = TasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/dev/components',
  path: '/dev/components',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdIndexRoute = TasksTaskIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksTaskIdRoute,
} as any)
const TasksTaskIdReviewRoute = TasksTaskIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => TasksTaskIdRoute,
} as any)
const TasksTaskIdArtifactsArtifactIdRoute =
  TasksTaskIdArtifactsArtifactIdRouteImport.update({
    id: '/artifacts/$artifactId',
    path: '/artifacts/$artifactId',
    getParentRoute: () => TasksTaskIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/dev/components': typeof DevComponentsRoute
  '/tasks/$taskId': typeof TasksTaskIdRouteWithChildren
  '/tasks/new': typeof TasksNewRoute
  '/tasks/$taskId/review': typeof TasksTaskIdReviewRoute
  '/tasks/$taskId/': typeof TasksTaskIdIndexRoute
  '/tasks/$taskId/artifacts/$artifactId': typeof TasksTaskIdArtifactsArtifactIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/dev/components': typeof DevComponentsRoute
  '/tasks/new': typeof TasksNewRoute
  '/tasks/$taskId/review': typeof TasksTaskIdReviewRoute
  '/tasks/$taskId': typeof TasksTaskIdIndexRoute
  '/tasks/$taskId/artifacts/$artifactId': typeof TasksTaskIdArtifactsArtifactIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/dev/components': typeof DevComponentsRoute
  '/tasks/$taskId': typeof TasksTaskIdRouteWithChildren
  '/tasks/new': typeof TasksNewRoute
  '/tasks/$taskId/review': typeof TasksTaskIdReviewRoute
  '/tasks/$taskId/': typeof TasksTaskIdIndexRoute
  '/tasks/$taskId/artifacts/$artifactId': typeof TasksTaskIdArtifactsArtifactIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/dev/components'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/tasks/$taskId/review'
    | '/tasks/$taskId/'
    | '/tasks/$taskId/artifacts/$artifactId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/dev/components'
    | '/tasks/new'
    | '/tasks/$taskId/review'
    | '/tasks/$taskId'
    | '/tasks/$taskId/artifacts/$artifactId'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/dev/components'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/tasks/$taskId/review'
    | '/tasks/$taskId/'
    | '/tasks/$taskId/artifacts/$artifactId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  DevComponentsRoute: typeof DevComponentsRoute
  TasksTaskIdRoute: typeof TasksTaskIdRouteWithChildren
  TasksNewRoute: typeof TasksNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/new': {
      id: '/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof TasksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/components': {
      id: '/dev/components'
      path: '/dev/components'
      fullPath: '/dev/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId/': {
      id: '/tasks/$taskId/'
      path: '/'
      fullPath: '/tasks/$taskId/'
      preLoaderRoute: typeof TasksTaskIdIndexRouteImport
      parentRoute: typeof TasksTaskIdRoute
    }
    '/tasks/$taskId/review': {
      id: '/tasks/$taskId/review'
      path: '/review'
      fullPath: '/tasks/$taskId/review'
      preLoaderRoute: typeof TasksTaskIdReviewRouteImport
      parentRoute: typeof TasksTaskIdRoute
    }
    '/tasks/$taskId/artifacts/$artifactId': {
      id: '/tasks/$taskId/artifacts/$artifactId'
      path: '/artifacts/$artifactId'
      fullPath: '/tasks/$taskId/artifacts/$artifactId'
      preLoaderRoute: typeof TasksTaskIdArtifactsArtifactIdRouteImport
      parentRoute: typeof TasksTaskIdRoute
    }
  }
}

interface TasksTaskIdRouteChildren {
  TasksTaskIdReviewRoute: typeof TasksTaskIdReviewRoute
  TasksTaskIdIndexRoute: typeof TasksTaskIdIndexRoute
  TasksTaskIdArtifactsArtifactIdRoute: typeof TasksTaskIdArtifactsArtifactIdRoute
}

const TasksTaskIdRouteChildren: TasksTaskIdRouteChildren = {
  TasksTaskIdReviewRoute: TasksTaskIdReviewRoute,
  TasksTaskIdIndexRoute: TasksTaskIdIndexRoute,
  TasksTaskIdArtifactsArtifactIdRoute: TasksTaskIdArtifactsArtifactIdRoute,
}

const TasksTaskIdRouteWithChildren = TasksTaskIdRoute._addFileChildren(
  TasksTaskIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  DevComponentsRoute: DevComponentsRoute,
  TasksTaskIdRoute: TasksTaskIdRouteWithChildren,
  TasksNewRoute: TasksNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
